import { createTheme } from "@uiw/codemirror-themes";
import { tags as t } from "@lezer/highlight";

export const myTheme = createTheme({
  dark: "light",
  settings: {
    background: "#ffffff",
    foreground: "#000000",
    caret: "#000000",
    selection: "#d6d6d6",
    selectionMatch: "#D6D6D6",
    gutterBackground: "#FFFFFF",
    gutterForeground: "#4D4D4C",
    gutterBorder: "#ddd",
    lineHighlight: "#EFEFEF",
  },
  styles: [
    { tag: t.comment, color: "#000000" },
    { tag: t.lineComment, color: "#a0a0a2" },
    { tag: t.name, color: "#000000" },
    { tag: t.definition(t.typeName), color: "#194a7b" },
    { tag: t.typeName, color: "#194a7b" },
    { tag: t.tagName, color: "#0a290b" },
    { tag: t.variableName, color: "#000000" },
    { tag: t.definition(t.variableName), color: "#000000" },
    { tag: t.function(t.variableName), color: "#000000" },
    { tag: t.propertyName, color: "#000000" },
    { tag: t.function(t.propertyName), color: "#000000" },
    { tag: t.definition(t.propertyName), color: "#000000" },
    { tag: t.special(t.propertyName), color: "#000000" },
    { tag: t.attributeName, color: "#000000" },
    { tag: t.labelName, color: "#ff0000" },
    { tag: t.namespace, color: "#000000" },
    { tag: t.operatorKeyword, color: "#000000" },
    { tag: t.controlKeyword, color: "#000000" },
    { tag: t.definitionKeyword, color: "#000000" },
    { tag: t.moduleKeyword, color: "#9402e3" },
    { tag: t.operator, color: "#000000" },
    { tag: t.derefOperator, color: "#000000" },
    { tag: t.angleBracket, color: "#000000" },
    { tag: t.squareBracket, color: "#000000" },
    { tag: t.brace, color: "#000000" },
    { tag: t.content, color: "#000000" },
    { tag: t.heading, color: "#f16609" },
    { tag: t.contentSeparator, color: "#000000" },
    { tag: t.quote, color: "#000000" },
    { tag: t.link, color: "#8e02e3" },
    // { tag: t.monospace, color: "#3a75fd" },
    { tag: t.strikethrough, color: "#000000" },
    { tag: t.inserted, color: "#e60f0f" },
    { tag: t.documentMeta, color: "#000000" },
    { tag: t.annotation, color: "#000000" },
    // { tag: t.processingInstruction, color: "#000000" },
  ],
});
